spring:
  application:
    name: product-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html